### ISSUE TITLE
Failure to compile protos with package

### ISSUE THREAD

**Issue by bryanhughes** [lrascao/rebar3_gpb_plugin#107]
I am having a problem compiling my project with rebar3 using the gpb plugin. It is erroring out on the `package service;` line in the .proto. All the protos compile with `protoc` without issue.

See the attached log for the output.
[output.log](https://github.com/lrascao/rebar3_gpb_plugin/files/3623907/output.log)

My project is set up as an umbrella project and the rebar.config for gpb is in the app directory where the protos are to be compiled.

I am attaching several screenshots of my project including one of the source for the proto in question.

![intellij-4](https://user-images.githubusercontent.com/21214/65095173-f74d9000-d974-11e9-807a-20b24d47f984.png)

![intellij-3](https://user-images.githubusercontent.com/21214/65089080-a50a7000-d970-11e9-95ce-379bcb15ecde.png)

Weirdly enough, at one point I was getting an error message like one of your closed issues that it could not find the file. That is no longer happening. Finally, I took your sample_app and modified it so that it had protos in different sub-directories and specified packages and it worked, so not sure what it is about my project that is causing this issue and why it manifests like this.

Thanks in advance!

**UPDATE**
I simplified the number of protos and tried to just remove the `package` from the proto, but unfortunately they still need to reference other packages. I got this output

[output-1.log](https://github.com/lrascao/rebar3_gpb_plugin/files/3623978/output-1.log)

**Comment by lrascao** [comment]
In order to rule out the plugin as the cause of your issue you could try and use the `bin/protoc-erl` tool directly from the [gpb](github.com:tomas-abrahamsson/gpb) project and apply it to each of your `.proto` files

**Comment by bryanhughes** [comment]
Doh... sorry, should have done that in the first place. The problem is with gpb itself. I will close this comment.

**Comment by bryanhughes** [comment]
There is an issue. My bug is due to the fact that `gpb` uses yecc so keywords like `service` are a problem. When I change the package name to `foobar` it correctly fails with the message:

```
bryan@Yetibuntu:~/git/gpb$ bin/protoc-erl -I. ~/git/rebar3_gpb_plugin/doc/samples/sample_app/proto/service/error.proto -o /tmp
hint: use the option use_packages (-pkgs) to use messages or enums in other packages
in msg Error, field details: undefined reference  google.protobuf.Any
```

When I run with the `-pkgs` option it works. The issue is that my protos reference some of Google external packages like Timestamp and Any.

Is there a way to get the plugin to append `-pkgs` to the command line?

**Comment by tomas-abrahamsson** [comment]
Use `gpb_opts` in the `rebar.config` to specify options to gpb. The option that corresponds to `-pkgs` is `use_packages`.

**Comment by lrascao** [comment]
i think that option it's already there in the screenshot posted of the rebar.config

**Comment by tomas-abrahamsson** [comment]
I'm aware of the problem of using keywords for instance for packages and message names, so far this is the first time I've heard someone raising concern over it. Can you work around it, or is it something that must be looked into? (Rewriting the parser/scanner might take some time, though)

**Comment by bryanhughes** [comment]
Yes, it is easy enough to not call the package `service`. That works. The problem is that our protobuffers reference external packages like `google.protobuf.Any` and `google.protobuf.Timestamp`. When I run the proto-erl directly on them with the `-pkgs` flag, everything works. So my problem is how to do I get the plugin to pass the `-pkgs` flag to proto-erl?

**Comment by bryanhughes** [comment]
I found the problem. For whatever reason, `rebar3 clean` did not work so I had to remove the `_build` directory. It is picking up the `{use_packages, true}`. So YAY!

Unfortunately, I hit this issue...
```
===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace or consult rebar3.crashdump
===> Uncaught error: {badmatch,
                             {error,
                              {post_process,
                               [{msg_multiply_defined,"public.CMessage"}]},
                              []}}
===> Stack trace to the error location:
[{rebar3_gpb_compiler,filter_included_proto,3,
                      [{file,"/home/bryan/git/gruvy/apps/gruvy_model/_build/default/plugins/rebar3_gpb_plugin/src/rebar3_gpb_compiler.erl"},
                       {line,160}]},
```
at https://github.com/lrascao/rebar3_gpb_plugin/blob/develop/src/rebar3_gpb_compiler.erl#L160

Which ended up showing that one of our protobufs had a bug in it and was recursively importing itself. Oops.
