### ISSUE TITLE
2.13.1 is not on hex.pm

### ISSUE THREAD

**Issue by michaelklishin** [lrascao/rebar3_gpb_plugin#115]
The docs in the README are currently not correct as they recommend version `2.13.1`. It was indeed [tagged](https://github.com/lrascao/rebar3_gpb_plugin/releases/tag/2.13.1) but not [released to Hex.pm](https://hex.pm/packages/rebar3_gpb_plugin).

**Comment by lrascao** [comment]
pushed to hex
