### ISSUE TITLE
Can you upgrade gpb deps to 4.14.0

### ISSUE THREAD

**Issue by bighunter513** [lrascao/rebar3_gpb_plugin#122]
My project use erlang + go grpc communication, 
and nested proto files contain "import public xxx.proto" for go grpc support , 
but  gpb support this feature from 4.14.0, or it will crash to generate erlang pb files

**Comment by lrascao** [comment]
done, [2.16.0](https://hex.pm/packages/rebar3_gpb_plugin/2.16.0) has been cut and pushed to hex
