### ISSUE TITLE
Folder `include` required even if unused

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [lrascao/rebar3_gpb_plugin#138]
I'm using the plugin with a maps-based approach (option `maps`), so no `o_hrl` is required.
I don't have an `include` folder (which the plugin "feels" it needs), so the plugin doesn't allow me to move forward (because of https://github.com/lrascao/rebar3_gpb_plugin/blob/develop/src/rebar3_gpb_compiler.erl#L36).
My alternatives, at the moment, are:

* create an empty `include` folder (with an empty file I have to push to remote), or
* use `o_hrl` = `src` so the check doesn't fail.

Since that check seems useless we could probably do without it.
I'm not sure `maps` is the only option that affects this.
I'm willing to implement whatever we agree upon so this isn't an impediment to others.

**Comment by paulo-ferraz-oliveira** [comment]
@lrascao also told me some of this might be eventually be closely related to the integration with `gpb` itself, in the sense that it'll lead what needs to be done (and the plugin probably will do it - e.g. create a folder). One other fast way to move forward, though, would be to only perform the check when a given file actually has to be created (just before).

**Comment by tomas-abrahamsson** [comment]
Yes, the gpb_compile:list_io/2 will include a `{hrl_output, DestFileName}` only when generating for records and not when generating for maps (and a `{nif_cc_output, DestFileName}` tuple if `nif`). But unfortunately, that offending is still there also in #136. Didn't think about that at the time...

**Comment by paulo-ferraz-oliveira** [comment]
How do you think it's best to proceed, here, @tomas-abrahamsson?

Pull request so that `include` isn't checked if unused? 
Wait for `gpb`?
Work around this, as per my initial description?

**Comment by tomas-abrahamsson** [comment]
> Pull request so that `include` isn't checked if unused?

Yes, I think this would be the best solution.

**Comment by paulo-ferraz-oliveira** [comment]
I have no time to work on this, at the moment. Feel free to re-open if deemed important.
