### ISSUE TITLE
Automatic updates for new version of gpb?

### ISSUE THREAD

**Issue by tomas-abrahamsson** [lrascao/rebar3_gpb_plugin#14]
Hi, is there something I could/should do from my side, whenever I push a new version of gpb, to make life easier for the rebar3_gpb_plugin? For example automatically creating a PR with the new version number in it? [It looks like it could be possible to do something automatically](https://developer.github.com/v3/pulls/#create-a-pull-request), and then it would be almost no extra work for me for each new gpb version. What do you think?

**Comment by lrascao** [comment]
Up until now is was bumping the plugin on re-request basis, the automatic way would be way cooler, if you don't mind integrating that into your workflow, thanks!

**Comment by lrascao** [comment]
thanks!
