### ISSUE TITLE
New versiof gpb: 4.17.1

### ISSUE THREAD

**Issue by tomas-abrahamsson** [lrascao/rebar3_gpb_plugin#140]
I've just pushed version 4.17.1 of gpb, but given the discussion in #139, how should we proceed? Will you just change the dependency to `"~> 4"` like @paulo-ferraz-oliveira suggested and no PR for 4.17.1 would be needed (if I understood right)? Or should I make some PR? (If so, what should it look like?)

**Comment by lrascao** [comment]
yeah, i guess that works, i'll merge 4.17.0 first and we can try it this way from now on

**Comment by lrascao** [comment]
just realized that a PR or an issue will still be needed so the new version can be locked, so we'll probably be keeping the same workflow @tomas-abrahamsson, probably your script can now be made a little bit simpler as it no longer needs to update rebar.config

**Comment by paulo-ferraz-oliveira** [comment]
> just realized that a PR or an issue will still be needed so the new version can be locked

Yeah, that's the only downside to it. In any case, when you upgrade a plugin `rebar3` doesn't really care about the lock. Good call, though.
