### ISSUE TITLE
hooks prevent compilation

### ISSUE THREAD

**Issue by Licenser** [lrascao/rebar3_gpb_plugin#33]
I've noticed some odd behaviour I'm not sure if that is a change in how rebar handles compilation now or when the plugin.

So here it what I figured out so far:

when compiling with the default settings and hooks the `_pb.erl` file gets put in `_build/default/lib/<app>/src` then when the "normal" compile happens rebar finds the src directory and doesn't copy the original files.

This can be worked around by changing the config to however that probably is not as it is supposed to work.

```
{gpb_opts, [
    {i, "proto"},
    {module_name_suffix, "_pb"},
    {o_erl, "../../../../apps/ddb_proxy/src"},
    {o_hrl, "../../../../apps/ddb_proxy/include"},
    {strings_as_binaries, true},
    type_specs]}.
```

**Comment by lrascao** [comment]
when you refer to the "normal" compile is it building with a profile (eg . `rebar3 as somehting compile`)?

**Comment by lrascao** [comment]
The `o_erl`  and `o_hrl` are appended to the app output dir given by `rebar3` so in a default profile would be `_build/default/lib/...` and on a live profile (for example) would be `_build/live/lib/...`, in light of this your `gpb_opts` should look something like this:

````
{gpb_opts, [
    {i, "proto"},
    {module_name_suffix, "_pb"},
    {o_erl, "apps/ddb_proxy/src"},
    {o_hrl, "apps/ddb_proxy/include"},
    {strings_as_binaries, true},
    type_specs]}.
````

**Comment by Licenser** [comment]
'Normas' as in: from the README file.

I noticed that it's appended however that does create the above mentioned problem with rebar after that no longer compiling the applications own source. Also despite the project directory being `apps/ddb_proxy/...` it will end up in `_build/default/lib/ddb_proxy/...` not`_build/default/lib/apps/ddb_proxy/...` so I don't think the `apps` or `ddb_proxy` part is right in the gpb_opts (but I might just misunderstand the whole concept)

**Comment by lrascao** [comment]
is this a branch where i can the problem happening: `https://github.com/dalmatinerdb/ddb_proxy/tree/dev/apps/ddb_proxy` ?

**Comment by lrascao** [comment]
the protobuf generated files are copied to whichever profile you selected, if none is chosen then it's `default`, if you try `rebar3 as deb compile` you'll see them ending up in `_build/deb/lib/ddb_proxy/apps/ddb_proxy/src`, i changed the `gpb_opts` to the one i mentioned above and did a couple of builds and couldn't find the issue, could you post a sequence of commands for me to try and reproduce it?

**Comment by Licenser** [comment]
So deleting `_build` and running `rebar3 compile`:

when the pathes are prefixed with: `apps/ddb_proxy/`

I get the following error:

```
===> Compiling apps/ddb_proxy/src/dp_prom_writer.erl failed
apps/ddb_proxy/src/dp_prom_writer.erl:4: can't find include file "remote_pb.hrl"

apps/ddb_proxy/src/dp_prom_writer.erl:10: record 'WriteRequest' undefined
apps/ddb_proxy/src/dp_prom_writer.erl:48: record 'TimeSeries' undefined
apps/ddb_proxy/src/dp_prom_writer.erl:49: variable 'Labels' is unbound
apps/ddb_proxy/src/dp_prom_writer.erl:53: variable 'Samples' is unbound
apps/ddb_proxy/src/dp_prom_writer.erl:56: record 'LabelPair' undefined
apps/ddb_proxy/src/dp_prom_writer.erl:57: variable 'Name' is unbound
apps/ddb_proxy/src/dp_prom_writer.erl:57: variable 'Value' is unbound
apps/ddb_proxy/src/dp_prom_writer.erl:68: variable 'T' is unbound
apps/ddb_proxy/src/dp_prom_writer.erl:69: record 'Sample' undefined
apps/ddb_proxy/src/dp_prom_writer.erl:70: variable 'V' is unbound
```

The files end up in:
```
MacBook-Pro:ddb_proxy heinz [grrr] $ find . -name remote_pb.hrl
./_build/default/lib/ddb_proxy/apps/ddb_proxy/include/remote_pb.hrl
```

Using the 'defults' `src` and `include` (again deleting `_build` before running any commands:

This compiles **but** the actual sorce files don't get compiled:
```
ddb_proxy $ ls ./_build/default/lib/ddb_proxy/src/
remote_pb.erl
```

**Comment by Licenser** [comment]
I've added the `grrr` branch that includes the original config (`src` and `include`)

**Comment by lrascao** [comment]
Here is a [patch](https://gist.github.com/lrascao/7f082d21e4a06a81e92ac3dfb788f1da) based on the `grrr` branch that fixes the issue, it basically moves the `gpb_opts` conf to a new rebar.config under the `ddb_proxy` app, when building the release rebar3 will pick up the app specific rebar.config

**Comment by Licenser** [comment]
figure this is worked out and documented :)
