### ISSUE TITLE
Can't find include file "gpb.hrl"

### ISSUE THREAD

**Issue by goofansu** [lrascao/rebar3_gpb_plugin#4]
FYI, rebar.config:

```
%% -*- mode: erlang; -*-

{erl_opts, [debug_info]}.
{deps, [{ranch, "1.2.1"}]}.
{plugins, [rebar3_gpb_plugin]}.
{provider_hooks, [
                  {pre, [{compile, {protobuf, compile}}]}
                 ]
}.
{gpb_opts, [
            {i, "./proto"},
            {o_erl, "./src"},
            {o_hrl, "./include"},
            {module_name_suffix, "_pb"},
            {strings_as_binaries, true},
            type_specs
           ]
}.
```

**Comment by goofansu** [comment]
Compiled after adding `{erl_opts, [{i, "./_build/default/plugins/gpb/include"}]` to `rebar.config`. Is it the correct way?

**Comment by lrascao** [comment]
right now that's the only way, maybe the plugin can do a search on the
current environment and set the correct dir

**Comment by goofansu** [comment]
Got it, thanks. Shall I open a pull request to add some document?

**Comment by lrascao** [comment]
Sure, that'd be great, thanks!

On Wednesday, 6 April 2016, YeJun Su <notifications@github.com> wrote:

> Got it, thanks. Shall I open a pull request to add some document?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/lrascao/rebar3_gpb_plugin/issues/4#issuecomment-206069562>
>


-- 
PGP fingerprint: F708 E141 AE8D 2D38 E1BC  DF3D 1719 3EA0 647D 7260

**Comment by goofansu** [comment]
PR added. Close.
