### ISSUE TITLE
Compilation doesn't work without provider hooks

### ISSUE THREAD

**Issue by wojtekmach** [lrascao/rebar3_gpb_plugin#72]
Steps to reproduce:

1. `git clone https://github.com/hexpm/hex_erl && cd hex_erl`
2. `rebar3 protobuf clean` - doesn't do anything
3. `rm -rf src/*pb* && rebar3 protobuf compile` - doesn't generate files
4. Add provider hooks
5. `rm -rf _build`
6. `rebar3 compile` - works
7. `rebar3 clean` - works

---

we'd like to use the plugin without provider hooks because hex_erl is meant to be used as a dependency, ~proto files~ generated .erl files are vendored in, and there should be no dependency on gpb. More context here: https://github.com/hexpm/hex_erl/issues/20

**Comment by lrascao** [comment]
If i:
1. `rm `find . -name '*_pb_*.erl'```
2. `DEBUG=1 rebar3 protobuf compile`

I'm seeing that .proto files get processed, i can find the generated .erl in `./_build/default/lib/hex_erl/src/`, can you try this as well?

**Comment by wojtekmach** [comment]
yes, I see generated files in `./_build/default/lib/hex_erl/src/` but not in `./src`; is that expected?

**Comment by lrascao** [comment]
yeah, .erl files get copied there by rebar3, the plugin just generates them there before the `compile` step to be picked up

**Comment by lrascao** [comment]
is there a reason to be including both the `.proto` files and the generated `.erl` files in the same repo?

**Comment by wojtekmach** [comment]
We vendor generated .erl files because the constraint of the project is to be dependency free so that:
1. Library can be embeded directly into mix, rebar3 and other build tools
2. Package can be used as a dependency by projects using any build tool, not just rebar3

For 1. we have a vendor.sh script and I suppose we could adjust it to copy generated .erl files at that moment, but for 2. we’d still want to support as wide range of packages and build tools as possible.

**Comment by wojtekmach** [comment]
We run into some issues with plugins so we ended up putting plugin and provider hooks into `dev` profile and run it with:

```
$ rebar3 as dev compile
```

and it works pretty well.
